**Bài tập:** Anh/chị sử dụng Google Colab sử dụng thuật toán KNN phân biệt loài hoa với tập dữ liệu train và test lần lượt là 80 và 70. Xét trường hợp K=5 đến K=10. Tìm trường hợp có độ chính xác cao nhất

In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

In [7]:
# Tải dữ liệu hoa iris và hiển thị vài dữ liệu mẫu. Các class được gán nhãn là 0, 1, và 2.
iris = load_iris()
iris_X = iris.data
iris_y = iris.target
print ('Number of classes: %d' %len(np.unique(iris_y)))
print ('Number of data points: %d' %len(iris_y))

X0 = iris_X[iris_y == 0,:]
print ('\nSamples from class 0:\n', X0[:5,:])

X1 = iris_X[iris_y == 1,:]
print ('\nSamples from class 1:\n', X1[:5,:])

X2 = iris_X[iris_y == 2,:]
print ('\nSamples from class 2:\n', X2[:5,:])

Number of classes: 3
Number of data points: 150

Samples from class 0:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

Samples from class 1:
 [[7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]]

Samples from class 2:
 [[6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]
 [6.3 2.9 5.6 1.8]
 [6.5 3.  5.8 2.2]]


In [10]:
# Tập dữ liệu train và test lần lượt là 80 và 70 => Lấy test 70 | Nếu tỷ lệ 80 - 20 => 0.2
X_train, X_test, y_train, y_test = train_test_split(iris_X, iris_y, test_size=70, random_state=42)
print ("Training size: %d" %len(y_train))
print ("Test size    : %d" %len(y_test))

Training size: 80
Test size    : 70


In [11]:
# Tiền xử lý dữ liệu bằng cách chuẩn hóa các đặc trưng
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [24]:
# Định nghĩa mô hình KNN với các giá trị K từ 5 đến 10
accuracies = []
for k in range(5, 11):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    accuracy = knn.score(X_test, y_test)
    accuracies.append(accuracy)
    print(f"K = {k} cho độ chính xác là {accuracy:.2f}")

K = 5 cho độ chính xác là 0.97
K = 6 cho độ chính xác là 0.96
K = 7 cho độ chính xác là 0.99
K = 8 cho độ chính xác là 0.99
K = 9 cho độ chính xác là 0.99
K = 10 cho độ chính xác là 0.99


In [26]:
# Tìm trường hợp có độ chính xác cao nhất
best_k = np.argmax(accuracies) + 5
best_accuracy = accuracies[best_k - 5]
print(f"K = {best_k} cho độ chính xác cao nhất là {best_accuracy:.2f}")

K = 2 cho độ chính xác cao nhất là 0.99


In [20]:
# Cố định k
k = 9
accuracies = []
knn = KNeighborsClassifier(n_neighbors=k)
knn.fit(X_train, y_train)
accuracy = knn.score(X_test, y_test)
print(f"K = {k} cho độ chính xác là {accuracy:.2f}")

K = 9 cho độ chính xác là 0.99
